stages:
  - test

specflow_test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1909
  timeout: 15 minutes
  variables:
    project_path: "./Demo_SpecflowPOM/POMPOCSpecflow/POMPOCSpecflow.csproj"      
  before_script:
    - dotnet tool install --global trx2junit --version 1.2.5
    - dotnet restore ${project_path}
    - dotnet build ${project_path} -c Debug
  script:
    - dotnet test ${project_path} -c Debug --logger:trx
  after_script:
    - cd ./Demo_SpecflowPOM/POMPOCSpecflow
    - mkdir TestResultsTRX
    - mkdir TestResultsXML
    - cd TestResults
    - ~/.dotnet/tools/trx2junit *.trx
    - cp *.trx ../TestResultsTRX
    - cp *.xml ../TestResultsXML
    - cd ../../../
  artifacts:
    when: always
    reports:
      junit:
        - './Demo_SpecflowPOM/POMPOCSpecflow/TestResultsXML/*.xml'
