.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - test

specflow_test:
  stage: test
  extends:
    - .shared_windows_runners
  image: mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1909
  timeout: 15 minutes
  variables:
    project_path: "./Demo_SpecflowPOM/POMPOCSpecflow/POMPOCSpecflow.csproj"      
    chrome_binary_path: "./Demo_SpecflowPOM/POMPOCSpecflow/chrome_installer.exe"
  before_script:
    - dotnet tool install --global trx2junit --version 1.2.5
    - dotnet build ${project_path} -c Debug
    - Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile ${chrome_binary_path}
    - Start-Process -FilePath ${chrome_binary_path} -Args "/silent /install" -Verb RunAs -Wait
  script:
    - dotnet test ${project_path} -c Debug --logger:trx
  after_script:
    - cd ./Demo_SpecflowPOM/POMPOCSpecflow
    - mkdir TestResultsTRX
    - mkdir TestResultsXML
    - cd TestResults
    - ~/.dotnet/tools/trx2junit *.trx
    - cp *.trx ../TestResultsTRX
    - cp *.xml ../TestResultsXML
    - cd ../../../
  artifacts:
    when: always
    reports:
      junit:
        - './Demo_SpecflowPOM/POMPOCSpecflow/TestResultsXML/*.xml'
